### ISSUE TITLE
CI should delete testing artifacts

### ISSUE THREAD

**Issue by giarc3** [IronCoreLabs/ironoxide-swig-bindings#145]
Our CI job (at least for android) splits up the building and testing into 2 Github Action jobs. It does this to parallelize the building and testing for different architectures. 

It uses the `upload-artifact` action so that the result of the build can be used by the test.
Unfortunately, these artifacts persist after the build completes and are using up our Github Actions storage. 

Anywhere that we use the `upload-artifact` action, we should have something in place to delete it once done. We could do this as the final step of the job, but then it wouldn't be deleted if the job failed before that.

**Comment by ernieturner** [comment]
Should be applied to other repos once we figure out the solution here.
