### ISSUE TITLE
Release 0.14.3 or publish iOS artifacts for 0.14.2

### ISSUE THREAD

**Issue by coltfred** [IronCoreLabs/ironoxide-swig-bindings#174]
0.14.2 doesn't have the .a file for iOS in the release. This means that we can't update the homebrew-ironcore to have this version. 

We should either try and re-run the workflow for 0.14.2 to get this published or release 0.14.3.

**Comment by giarc3** [comment]
I think we'll have to release 0.14.3, as re-running 0.14.2 will end up with the same issue failing to upload android 0.14.2 (which was manually uploaded to maven) before it gets to the step that would upload the iOS artifacts.
