### ISSUE TITLE
`ironoxide-android v0.14.3

### ISSUE THREAD

**Issue by GaoWhitebird** [IronCoreLabs/ironoxide-swig-bindings#193]
error: failed to run custom build command for `ironoxide-android v0.14.3 (/Volumes/…/ironoxide-swig-bindings/android)`

Caused by:
  process didn't exit successfully: `/target/debug/build/ironoxide-android-67e8990516a3b9e6/build-script-build` (exit status: 101)
  --- stdout
  Run rust_swig_expand

  --- stderr
  thread 'main' panicked at 'Error during running of rustfmt: Cannot find binary path', /Users/…/.cargo/git/checkouts/rust_swig-b67a7d3216ea50ac/1835ebd/macroslib/src/lib.rs:574:17
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by BobWall23** [comment]
This occurred because `rustfmt` was being called to format the generated source, and it wasn't installed.
Resolution is to not format the generated source.

**Comment by giarc3** [comment]
`ironoxide-android v0.14.7` was released today, and it no longer requires `rustfmt` during the build process. Depending on this version should fix the error you posted, but please let us know if you need any further assistance!
