### ISSUE TITLE
Auth0 Social login - jwt validation issue

### ISSUE THREAD

**Issue by GaoWhitebird** [IronCoreLabs/ironoxide-swig-bindings#207]
Auth0 social login 

Jwt jwtIron = Jwt.validate("token");

I tried above code but it is showing this error.
Could you help me please ?
Thanks.

java.lang.Exception: 'jwt' failed validation with the error 'JSON error: duplicate field `sid` at line 1 column 625'

**Comment by BobWall23** [comment]
An issue with more detail has been created here https://github.com/IronCoreLabs/ironoxide/issues/280

**Comment by giarc3** [comment]
This was due to prefixed and non-prefixed claims being used in conjunction.
This should be fixed as of v0.15.0
